name: "Merge on LGTM Label"
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: chnsz/prow-github-actions@master
        with:
          jobs: 'lgtm'
          github-token: "${{ secrets.PAT }}"
          # this configuration is optional and will default to 'merge'
          # possible options are 'merge', 'rebase', or 'squash'
          merge-method: 'squash'
