name: "Run Jobs on PR"
on:
  pull_request_target:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prow action
        uses: chnsz/prow-github-actions@v1.0.0
        with:
          github-token: "${{ secrets.PAT }}"
          jobs: lgtm
