name: "Run Jobs on PR"
on: pull_request

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Prow action
        uses: chnsz/prow-github-actions@v1.0.0
        with:
          github-token: "${{ secrets.PAT }}"
          jobs: lgtm
